from .pacienteSerializer import PacienteSerializer
from .usuarioSerializer import UsuarioSerializer
from .enfermeroSerializer import EnfermeroSerializer
from .familiarSerializer import FamiliarSerializer
from .medicoSerializer import MedicoSerializer
from .signosvitalesSerializer import SignosVitalesSerializer
from .diagnosticoSerializer import DiagnosticoSerializer
from .historiaclinicaSerializer import HistoriaClinicaSerializer
